### ISSUE TITLE
"Filename or extension is too long" error upon trying to play level

### ISSUE THREAD

**Issue by BobBobstien** [leveleditor/CAMM-Crystal-Alien-Map-Maker#8] opened 2019-10-07 18:57 UTC
[OpsFinal.zip](https://github.com/leveleditor/CAMM-Crystal-Alien-Map-Maker/files/3699002/OpsFinal.zip)

**Comment by BobBobstien** [comment] 2019-10-07 19:02
It also brings up the "might not be saved" warning upon trying to quit the program, but it seems to save correctly

**Comment by BobBobstien** [comment] 2019-10-07 20:13
Upon further investigation the present unit is that seems to break things.

**Comment by Landlighter** [comment] 2020-03-30 15:28
I think it actually is an overflow. Once you have a certain number of units / buildings / map size it's too large for the player to handle

**Comment by leveleditor** [comment] 2020-05-04 23:53
The cause of this issue was something I originally overlooked.

The way the maps are being passed over to the CAC Player is currently by encoding the map file contents as a Base64 string and passing it to the same command line that opens the CAC Player.

This worked well in theory, and does work for small map files, but once the map files reach a certain size, most notably by adding "just one more unit or building", the encoded Base64 string exceeds the maximum command line length of the operating system which results in this misleading error.
The "filename" in the error is actually referring to the command line.

I thought of a few different ways to fix this, all involving switching to a different method of passing the map contents over, and will hopefully be exploring these options soon.

**Comment by leveleditor** [comment] 2020-05-08 03:34
This is now fixed as of the latest code commit (0a698bf4a46744404715df2422b35720d915767f)

You'll need to download the updated version of both CAMM and CAC Player:
https://crystalien-redux.com/camm.php

Fixed as of these versions:
CAMM version 1.4.0.59
CAC Player version 1.3.1

**Closed as completed by leveleditor** 2020-05-08 03:34 UTC
Labels: bug
